# This workflow will test this Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Test with Maven

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Java 14
        uses: actions/setup-java@v1
        with:
          java-version: 14
      - name: install settings.xml
        uses: s4u/maven-settings-action@v2.1.1
        with:
          servers: '[{"id": "github", "username": "${{github.actor}}", "password": "${{secrets.github_token}}"}]'
      - name: mvn test
        run: mvn clean test --file pom.xml --no-transfer-progress
