# This workflow will test this Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: release

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Java 14
        uses: actions/setup-java@v1
        with:
          java-version: 14
      - name: install settings.xml
        uses: s4u/maven-settings-action@v2.3.0
        with:
          servers: '[{"id": "github-cliserkad-smp", "username": "${{github.actor}}", "password": "${{secrets.github_token}}"}]'
      - name: mvn install
        run: mvn clean install --file pom.xml --no-transfer-progress
      - name: show changes
        run: bash ./changes.sh
      - name: create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: auto_tag_${{ github.sha }}
          release_name: auto_release_${{ github.sha }}
          body: ${{ env.CHANGES }}
          draft: false
          prerelease: false
      - name: attach jar
        id: attach_jar
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: /home/runner/.m2/repository/com/xarql/bitter/1/bitter-1-jar-with-dependencies.jar
          asset_name: bitter.jar
          asset_content_type: application/java-archive
      - name: attach windows install script
        id: attach_bat
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: src/main/resources/install/windows/installer.bat
          asset_name: windows_installer.bat
